version: '3.8'

services:
  laravel:
    build:
      context: .
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  react:
    build:
      context: ./react
    container_name: react_app
    ports:
      - "3000:3000"
    volumes:
      - ./react:/app
    depends_on:
      - laravel

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_app
    ports:
      - "3307:3306"