FROM node:18
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG VITE_API_BASE_URL=http://localhost:8000
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host"]