---
- hosts: local
  become: no

  tasks:
    - name: Run docker-compose
      shell: docker-compose down --remove-orphans && docker-compose up --build -d
      args:
        chdir: /var/jenkins_home/workspace/crud-pipeline